/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 5.4.0
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://localhost:8081";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/books", () => {
        let calificacion = 'TODO_EDIT_THE_CALIFICACION'; // specify value as there is no example value for this parameter in OpenAPI spec
        let precio = 'TODO_EDIT_THE_PRECIO'; // specify value as there is no example value for this parameter in OpenAPI spec
        let visible = 'TODO_EDIT_THE_VISIBLE'; // specify value as there is no example value for this parameter in OpenAPI spec
        let categoria = 'TODO_EDIT_THE_CATEGORIA'; // specify value as there is no example value for this parameter in OpenAPI spec
        let isbn = 'TODO_EDIT_THE_ISBN'; // specify value as there is no example value for this parameter in OpenAPI spec
        let titulo = 'TODO_EDIT_THE_TITULO'; // specify value as there is no example value for this parameter in OpenAPI spec
        let autor = 'TODO_EDIT_THE_AUTOR'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/books?titulo=${titulo}&autor=${autor}&categoria=${categoria}&isbn=${isbn}&calificacion=${calificacion}&visible=${visible}&precio=${precio}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/books`;
            // TODO: edit the parameters of the request body.
            let body = {"titulo": "string", "autor": "string", "fechapublicacion": "date", "categoria": "string", "isbn": "string", "precio": "double", "calificacion": "integer", "visible": "boolean", "stock": "integer"};
            let params = {headers: {"Content-Type": "application/json", "Accept": "*/*"}};
            let request = http.post(url, JSON.stringify(body), params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

    group("/books/{id}", () => {
        let id = 'TODO_EDIT_THE_ID'; // specify value as there is no example value for this parameter in OpenAPI spec

        // Request No. 1
        {
            let url = BASE_URL + `/books/${id}`;
            let request = http.get(url);

            check(request, {
                "OK": (r) => r.status === 200
            });

            sleep(SLEEP_DURATION);
        }

        // Request No. 2
        {
            let url = BASE_URL + `/books/${id}`;
            let params = {headers: {"Content-Type": "application/json", "Accept": "*/*"}};
            let request = http.patch(url, params);

            check(request, {
                "OK": (r) => r.status === 200
            });
        }
    });

}
